name: dicp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - tensorboard
  - pyyaml
  - pip:
      - torch
      - matplotlib
      - python-dateutil
      - networkx
      - einops
      - numpy
      - tqdm
      - transformers
      - accelerate
      - xformers
      - tensorboard
      - ninja
      - stable-baselines3
      - h5py
      - lightning